apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: larsito-dk-tls
spec:
  secretName: larsito-dk
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: larsito.dk
  dnsNames:
    - larsito.dk
    - www.larsito.dk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - larsito.dk
          - www.larsito.dk
